service: my-express-application

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  runtime: nodejs14.x
  environment:
    API_KEY: ${{ secrets.API_KEY }}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

custom:
  stage: "${opt:stage, 'dev'}"
