service: my-express-application

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.stage}
  # lambdaHashingVersion: "20201221"
  environment:
    API_KEY: ${env:API_KEY}

plugins:
  - serverless-plugin-typescript

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

custom:
  stage: "${opt:stage, 'dev'}"
